import { toast } from 'sonner';
import { Client } from '@/types';
import { services } from '@/mock/services';
import { FormData } from './useClientFormState';
import { 
  addClient as addClientToSupabase, 
  updateClient as updateClientInSupabase,
  deleteClient as deleteClientFromSupabase
} from '@/utils/clients';

interface UseClientOperationsProps {
  clients: Client[];
  setClients: React.Dispatch<React.SetStateAction<Client[]>>;
  resetForm: () => void;
  setIsAddClientOpen: (isOpen: boolean) => void;
  setIsEditClientOpen: (isOpen: boolean) => void;
  setIsDeleteClientOpen: (isOpen: boolean) => void;
  setSelectedClient: (client: Client | null) => void;
}

export const useClientOperations = ({
  clients,
  setClients,
  resetForm,
  setIsAddClientOpen,
  setIsEditClientOpen,
  setIsDeleteClientOpen,
  setSelectedClient,
}: UseClientOperationsProps) => {
  
  const handleAddClient = async (formData: FormData) => {
    // Simple validation
    if (!formData.companyName || !formData.email || !formData.selectedServiceId) {
      toast.error('Preencha todos os campos obrigatórios');
      return;
    }

    const selectedService = services.find(s => s.id === formData.selectedServiceId);
    
    if (!selectedService) {
      toast.error('Selecione um serviço válido');
      return;
    }

    const newClient: Omit<Client, 'id'> = {
      companyName: formData.companyName,
      tradeName: formData.tradeName,
      document: formData.document,
      email: formData.email,
      phone: formData.phone,
      address: formData.address,
      startDate: formData.startDate,
      endDate: formData.endDate,
      loyaltyMonths: formData.loyaltyMonths,
      value: formData.value,
      dueDay: formData.dueDay,
      services: [
        {
          id: '', // Will be generated by the database
          clientId: '', // Will be set by the database
          serviceId: formData.selectedServiceId,
          service: selectedService,
          locationIds: formData.locationIds,
          startDate: formData.startDate,
          endDate: formData.endDate,
          value: formData.value,
        },
      ],
    };

    try {
      const addedClient = await addClientToSupabase(newClient);
      
      if (addedClient) {
        setClients(prev => [...prev, addedClient]);
        setIsAddClientOpen(false);
        resetForm();
        toast.success('Cliente adicionado com sucesso!');
      }
    } catch (error) {
      console.error('Error in handleAddClient:', error);
      toast.error('Erro ao adicionar cliente');
    }
  };

  const handleEditClient = async (formData: FormData, selectedClient: Client | null) => {
    if (!selectedClient) return;

    // Simple validation
    if (!formData.companyName || !formData.email) {
      toast.error('Preencha todos os campos obrigatórios');
      return;
    }

    const selectedService = formData.selectedServiceId 
      ? services.find(s => s.id === formData.selectedServiceId)
      : selectedClient.services[0]?.service;

    if (!selectedService) {
      toast.error('Selecione um serviço válido');
      return;
    }

    // Update client service if service changed
    const updatedServices = [...selectedClient.services];
    if (formData.selectedServiceId && formData.selectedServiceId !== selectedClient.services[0]?.serviceId) {
      updatedServices[0] = {
        ...updatedServices[0],
        serviceId: formData.selectedServiceId,
        service: selectedService,
        locationIds: formData.locationIds,
        startDate: formData.startDate,
        endDate: formData.endDate,
        value: formData.value,
      };
    }

    const updatedClient: Client = {
      ...selectedClient,
      companyName: formData.companyName,
      tradeName: formData.tradeName,
      document: formData.document,
      email: formData.email,
      phone: formData.phone,
      address: formData.address,
      startDate: formData.startDate,
      endDate: formData.endDate,
      loyaltyMonths: formData.loyaltyMonths,
      value: formData.value,
      dueDay: formData.dueDay,
      services: updatedServices,
    };

    try {
      const updatedDbClient = await updateClientInSupabase(updatedClient);
      
      if (updatedDbClient) {
        setClients(prev => prev.map(client => 
          client.id === selectedClient.id ? updatedDbClient : client
        ));
        setIsEditClientOpen(false);
        setSelectedClient(null);
        resetForm();
        toast.success('Cliente atualizado com sucesso!');
      }
    } catch (error) {
      console.error('Error in handleEditClient:', error);
      toast.error('Erro ao atualizar cliente');
    }
  };

  const handleDeleteClient = async (selectedClient: Client | null) => {
    if (!selectedClient) return;

    try {
      const success = await deleteClientFromSupabase(selectedClient.id);
      
      if (success) {
        setClients(prev => prev.filter(client => client.id !== selectedClient.id));
        setIsDeleteClientOpen(false);
        setSelectedClient(null);
        toast.success('Cliente removido com sucesso!');
      }
    } catch (error) {
      console.error('Error in handleDeleteClient:', error);
      toast.error('Erro ao remover cliente');
    }
  };

  return {
    handleAddClient,
    handleEditClient,
    handleDeleteClient,
  };
};
