// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyqqjxrzaleyawgmntpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5cXFqeHJ6YWxleWF3Z21udHBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MDAyMTQsImV4cCI6MjA2MjA3NjIxNH0.-3oCuT1qEfVlqkQlf2zZZBaY5Etfb5tamCvu-2Xucu8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);